a=int(input("enter you first number:"))
b=int(input("enter your second number:"))
sum=a+b
print("sum is =",sum)
diff=a-b
print("diff is =",diff)
mul=a*b
print("mul is =",mul)
quo=a/b
print("quo is =",quo)
remain=a%b
print("remain is =",remain)
power=a**b
print("power is =",power)
intd=a//b
print("the integer division is =",intd)
